name: Build
on: 
  workflow_dispatch:
  push:
    branches: [ "workflow_dispatch" ]
  pull_request:
    branches: [ "workflow_dispatch" ]
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login Github
      run: docker login ghcr.io --username arthurbentivenha --password=${{ secrets.REGISTRY }}
    - name: Criando a Imagem
      run: docker build  --platform linux/amd64 -t bolao .
    - name: Tag na imagem
      run: docker tag bolao ghcr.io/arthurbentivenha/bolao:${{github.run_number}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push ARM image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/arm64
        tags: ghcr.io/arthurbentivenha/bolao_arm:${{github.run_number}}
    - name: Publicando a imagem no Docker 
      run: docker push ghcr.io/arthurbentivenha/bolao_arm:${{github.run_number}}
